name: Bump version & deploy

on:
  push:
    branches:
      - main

jobs:
  bump-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # disable default creds

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version in index.html
        run: |
          sed -i "s/%APP_VERSION%/v1.$GITHUB_RUN_NUMBER/" index.html
          sed -i "s/%BUILD_TIME%/$(date)/" index.html

      - name: Commit & Push
        run: |
          git add index.html
          git commit -m "Bump version [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}